set output status manually

diff --git a/linux-check/action.yml b/linux-check/action.yml
--- a/linux-check/action.yml
+++ b/linux-check/action.yml
@@ -46,15 +46,9 @@ runs:
 
     - name: Build and check package
       shell: bash
-      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
+      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}} || true
       env:
         R_CHECK_ENVIRON: ${{github.action_path}}/../check.Renviron
-
-    - name: Parse CMD check results
-      if: always()
-      id: conclude
-      run: Rscript "${GITHUB_ACTION_PATH}/../results.R"
-      shell: bash
 
     - name: Inspect check outputs
       if: always()
@@ -73,3 +67,15 @@ runs:
         fi
         find . -regex '.*\.R*out' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
         find . -regex '.*\.fail' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
+
+    - name: Parse CMD check results
+      id: conclude
+      run: Rscript "${GITHUB_ACTION_PATH}/../results.R"
+      shell: bash
+
+# Fail manually instead of 'exit 1' to avoid annotation: https://stackoverflow.com/a/73532770/318752 
+    - name: Set failed conclusion
+      if: steps.conclude.outputs.CHECKSTATUS == 'ERROR'
+      uses: actions/github-script@v7
+      with:
+        script: core.setFailed()
diff --git a/macos-check/action.yml b/macos-check/action.yml
--- a/macos-check/action.yml
+++ b/macos-check/action.yml
@@ -37,20 +37,15 @@ runs:
         R_ENVIRON_USER: ${{github.action_path}}/../check.Renviron
         R_PROFILE_USER: ${{github.action_path}}/../Rprofile
 #        R_COMPILE_AND_INSTALL_PACKAGES: never
+
     - name: Build and check package
       shell: bash
-      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}}
+      run: R CMD check ${{inputs.sourcepkg}} --install-args="--build" ${{inputs.checkargs}} || true
       env:
         MACOSX_DEPLOYMENT_TARGET: 11.0
 #        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
         R_CHECK_ENVIRON: ${{github.action_path}}/../check.Renviron
         R_PROFILE_USER: ${{github.action_path}}/../Rprofile
-
-    - name: Parse CMD check results
-      if: always()
-      id: conclude
-      run: Rscript "${GITHUB_ACTION_PATH}/../results.R"
-      shell: bash
 
     - name: Inspect check outputs
       if: always()
@@ -71,3 +66,15 @@ runs:
         fi
         find . -regex '.*\.R*out' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
         find . -regex '.*\.fail' | while read f; do echo "::group::$f"; echo " ===== $f ====="; tail -n1000 $f; echo "::endgroup::"; done
+
+    - name: Parse CMD check results
+      id: conclude
+      run: Rscript "${GITHUB_ACTION_PATH}/../results.R"
+      shell: bash
+
+# Fail manually instead of 'exit 1' to avoid annotation: https://stackoverflow.com/a/73532770/318752 
+    - name: Set failed conclusion
+      if: steps.conclude.outputs.CHECKSTATUS == 'ERROR'
+      uses: actions/github-script@v7
+      with:
+        script: core.setFailed()
